//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BonoCorpAleman
{
    using System;
    using System.Collections.Generic;
    
    public partial class Costes_Gastos
    {
        public int ID { get; set; }
        public long Bono_ID { get; set; }
        public string Nombre { get; set; }
        public int Valor { get; set; }
        public bool Inicial { get; set; }
        public bool Emisor { get; set; }
        public bool Receptor { get; set; }
    
        public virtual Bono Bono { get; set; }
    }
}
