//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BonoCoporativoAleman
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bono
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bono()
        {
            this.Costes_Gastos = new HashSet<Costes_Gastos>();
            this.Inflacion1 = new HashSet<Inflacion>();
            this.PlazoBono = new HashSet<PlazoBono>();
        }
    
        public long BonoID { get; set; }
        public string Entidad_ID { get; set; }
        public int ValorNominal { get; set; }
        public int ValorComercial { get; set; }
        public int NroAnios { get; set; }
        public int FrecCupon { get; set; }
        public int DiasPorAnio { get; set; }
        public int TipoTasa { get; set; }
        public int Capitalizacion { get; set; }
        public int TasaInteres { get; set; }
        public int TasaAnualDesc { get; set; }
        public int ImpuestoRenta { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public int Inflacion { get; set; }
    
        public virtual Capitalizacion Capitalizacion1 { get; set; }
        public virtual Entidad Entidad { get; set; }
        public virtual TipoTasa TipoTasa1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Costes_Gastos> Costes_Gastos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inflacion> Inflacion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlazoBono> PlazoBono { get; set; }
    }
}
