//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BonoCorpAleman.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bono
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bono()
        {
            this.Bono_Tasa = new HashSet<Bono_Tasa>();
            this.Costes_Gastos = new HashSet<Costes_Gastos>();
            this.Inflacion = new HashSet<Inflacion>();
            this.PlazoBono = new HashSet<PlazoBono>();
        }
    
        public long BonoID { get; set; }
        public string Entidad_ID { get; set; }
        public decimal ValorNominal { get; set; }
        public int ValorComercial { get; set; }
        public int NroAnios { get; set; }
        public int FrecCupon { get; set; }
        public int DiasPorAnio { get; set; }
        public int ImpRenta { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public int TasaAnualDescuento { get; set; }
    
        public virtual Entidad Entidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bono_Tasa> Bono_Tasa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Costes_Gastos> Costes_Gastos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inflacion> Inflacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlazoBono> PlazoBono { get; set; }
    }
}
