//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BonoCorpAleman.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bono_Tasa
    {
        public int ID { get; set; }
        public int TipoTasa_ID { get; set; }
        public long Bono_BonoID { get; set; }
        public double TasaInteres { get; set; }
        public int NroCuota { get; set; }
        public Nullable<int> capitalizacion { get; set; }
    
        public virtual Bono Bono { get; set; }
        public virtual Capitalizacion Capitalizacion1 { get; set; }
        public virtual TipoTasa TipoTasa { get; set; }
    }
}
